const SET_ALL_TRANSACTION = "SET_ALL_TRANSACTION";
const SET_SYMBOL_TRANSACTION = "SET_SYMBOL_TRANSACTION";
const SET_TYPES_TRANSACTION = "SET_TYPES_TRANSACTION";
const SET_CRTYPTO_HISTORY = "SET_CRTYPTO_HISTORY";
const SET_TRANSACTION_HISTORY = "SET_TRANSACTION_HISTORY";

export default {
  SET_ALL_TRANSACTION,
  SET_SYMBOL_TRANSACTION,
  SET_TYPES_TRANSACTION,
  SET_CRTYPTO_HISTORY,
  SET_TRANSACTION_HISTORY,
};
